import React from "react";
import * as FaIcons from "react-icons/fa";
export const SidebarData = [
  {
    title: "About",
    path: "/about",
    iconClosed: "url(./nav-button_right-arrow.png)",
    iconOpened: "url(./nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [],
  },
  {
    title: "Projects",
    path: "/projects",
    iconClosed: "url(./nav-button_right-arrow.png)",
    iconOpened: "url(./nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [
      {
        title: "Sthocastic H.G",
        path: "/projects/55978965a31d4355b1190d0059189924",
        icon: "url(./nav-button.png)",
        subNav: [],
        cName: "sub-nav",
      },
      {
        title: "Urban Networks",
        path: "/projects/fb1b9e08f84842b39f014742343ccc4e",
        icon: "url(./nav-button.png)",
        subNav: [],
        cName: "sub-nav",
      },
      {
        title: "Text Recognizer",
        path: "/projects/9fa38b45c12647b68afec7587b944b20",
        icon: "url(./nav-button.png)",
        subNav: [],
      },
    ],
  },
  {
    title: "Backend",
    path: "/backend",
    iconClosed: "url(./nav-button_right-arrow.png)",
    iconOpened: "url(./nav-button_bottom-arrow.png)",
    icon: "url(./nav-button.png)",
    subNav: [
      {
        title: "Flask API",
        path: "/backend/55978965a31d4355b1190d0059189924",
        icon: "url(./nav-button.png)",
        subNav: [],
        cName: "sub-nav",
      },
    ],
  },
  {
    title: "Machine learning",
    path: "/machine-learning",
    iconClosed: "url(./nav-button_right-arrow.png)",
    iconOpened: "url(./nav-button_bottom-arrow.png)",
    icon: "url(./nav-button.png)",
    subNav: [],
  },
  {
    title: "Data Engineering",
    path: "/data-engineering",
    iconClosed: "url(/nav-button_right-arrow.png)",
    iconOpened: "url(/nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [],
  },
  {
    title: "Data Science",
    path: "/data-engineering",
    iconClosed: "url(/nav-button_right-arrow.png)",
    iconOpened: "url(/nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [],
  },
  {
    title: "Cloud Computing",
    path: "/cloud-compuing",
    iconClosed: "url(/nav-button_right-arrow.png)",
    iconOpened: "url(/nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [],
  },
  {
    title: "Algorithms&DS",
    path: "/algorithms-datastructures",
    iconClosed: "url(/nav-button_right-arrow.png)",
    iconOpened: "url(/nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [],
  },
  {
    title: "Contact",
    path: "/contact",
    iconClosed: "url(/nav-button_right-arrow.png)",
    iconOpened: "url(/nav-button_bottom-arrow.png)",
    icon: "url(/nav-button.png)",
    subNav: [],
  },
];
